// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	order "OrderManagement/OrderManagement/internal/handler/order"
	product "OrderManagement/OrderManagement/internal/handler/product"
	"OrderManagement/OrderManagement/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order",
				Handler: order.AddOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/order",
				Handler: order.ListOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/order",
				Handler: order.UpdateOrderHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/product",
				Handler: product.AddProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/product",
				Handler: product.UpdateProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/product",
				Handler: product.ListProductHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
