// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package handler

import (
	"net/http"

	auth "OrderManagement/OrderManagement/internal/handler/auth"
	order "OrderManagement/OrderManagement/internal/handler/order"
	product "OrderManagement/OrderManagement/internal/handler/product"
	shop "OrderManagement/OrderManagement/internal/handler/shop"
	users "OrderManagement/OrderManagement/internal/handler/users"
	"OrderManagement/OrderManagement/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/captcha",
				Handler: auth.CaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/logout",
				Handler: auth.LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refresh-token",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order",
				Handler: order.AddOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/order",
				Handler: order.ListOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/order",
				Handler: order.UpdateOrderHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/product",
				Handler: product.AddProductHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/product",
				Handler: product.UpdateProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/product",
				Handler: product.ListProductHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/product/sales/trend",
				Handler: product.GetProductSalesStatsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/shop",
				Handler: shop.AddShopHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/shop",
				Handler: shop.UpdateShopHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/shop",
				Handler: shop.ListShopHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/shop/sales/stats",
				Handler: shop.GetShopSalesStatsHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/users",
				Handler: users.AdduserHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/users/:ids",
				Handler: users.DeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/users/:userId",
				Handler: users.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/:userId/form",
				Handler: users.UserFormHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/:userId/profile",
				Handler: users.ProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/users/me",
				Handler: users.MeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/users/page",
				Handler: users.PageHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
	)
}
