// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package model

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

type invoiceDetailModel interface {
	Insert(ctx context.Context, data *InvoiceDetail) error
	FindOne(ctx context.Context, id string) (*InvoiceDetail, error)
	Update(ctx context.Context, data *InvoiceDetail) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
}

type defaultInvoiceDetailModel struct {
	conn *mon.Model
}

func newDefaultInvoiceDetailModel(conn *mon.Model) *defaultInvoiceDetailModel {
	return &defaultInvoiceDetailModel{conn: conn}
}

func (m *defaultInvoiceDetailModel) Insert(ctx context.Context, data *InvoiceDetail) error {
	if data.ID=="" {
		data.ID = primitive.NewObjectID().String()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

func (m *defaultInvoiceDetailModel) FindOne(ctx context.Context, id string) (*InvoiceDetail, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data InvoiceDetail

	err = m.conn.FindOne(ctx, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultInvoiceDetailModel) Update(ctx context.Context, data *InvoiceDetail) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now()

	res, err := m.conn.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultInvoiceDetailModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return 0, ErrInvalidObjectId
	}

	res, err := m.conn.DeleteOne(ctx, bson.M{"_id": oid})
	return res, err
}
