// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package model

import (
	"OrderManagement/OrderManagement/internal/common/errorx"
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

type menuModel interface {
	Insert(ctx context.Context, data *Menu) error
	FindOne(ctx context.Context, id int) (*Menu, error)
	Update(ctx context.Context, data *Menu) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
}

type defaultMenuModel struct {
	conn *mon.Model
}

func newDefaultMenuModel(conn *mon.Model) *defaultMenuModel {
	return &defaultMenuModel{conn: conn}
}

func (m *defaultMenuModel) Insert(ctx context.Context, data *Menu) error {
	if data.ID ==0 {
		// todo generate id
		return errorx.NoIdError 
	
	}

	data.CreateAt = time.Now()
	data.UpdateAt = time.Now()

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

func (m *defaultMenuModel) FindOne(ctx context.Context, id int) (*Menu, error) {


	var data Menu

	err := m.conn.FindOne(ctx, &data, bson.M{"_id": id})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMenuModel) Update(ctx context.Context, data *Menu) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now()

	res, err := m.conn.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultMenuModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return 0, ErrInvalidObjectId
	}

	res, err := m.conn.DeleteOne(ctx, bson.M{"_id": oid})
	return res, err
}
