// Code generated by goctl. DO NOT EDIT.
package types

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}

type PostProduct struct {
	Name          string `json:"name,omitempty"`          // 商品名称
	Price         Price  `json:"price,omitempty"`         // 商品价格
	Specification int    `json:"specification,omitempty"` // 规格
	IsActive      bool   `json:"isActive,omitempty"`      // 是否生效
	Image         string `json:"image,omitempty"`         // 图片
	NickName      string `json:"nickName,omitempty"`      // 别名
	BarCode       string `json:"barCode,omitempty"`       //条码
}

type ListProductReq struct {
	ProductId string `json:"productId,optional"`
	Name      string `json:"name,optional"`     // 商品名称
	IsActive  bool   `json:"isActive,optional"` // 是否生效
	NickName  string `json:"nickName,optional"` // 别名
	BarCode   string `json:"barCode,optional"`  //条码
}

type ListProductResp struct {
	Items []*Product `json:"items"`
	Count int        `json:"count"`
}

type Product struct {
	ProductId     string `json:"productId"`
	Name          string `json:"name,omitempty"` // 商品名称
	Price         Price  `json:"price,omitempty"`
	Specification int    `json:"specification,omitempty"` // 规格
	IsActive      bool   `json:"isActive,omitempty"`      // 是否生效
	Image         string `json:"image,omitempty"`         // 图片
	NickName      string `json:"nickName,omitempty"`      // 别名
	BarCode       string `json:"barCode,omitempty"`       //条码
}

type Price struct {
	Terminal  float64 `json:"terminal,omitempty"`  // 终端零售价
	WholeSale float64 `json:"wholesale,omitempty"` // 批发零售价
	Cost      float64 `json:"cost,omitempty"`      // 进价
	SRP       float64 `json:"srp,omitempty"`       // 建议零售价 Suggested Retail Price
	Warning   float64 `json:"warning,omitempty"`   // 报警价格
}

type PostOrder struct {
	Products    []*Products `json:"products,optional"`
	ShopId      string      `json:"shopId"`
	ShopName    string      `json:"shopName"`
	Address     string      `json:"address"`
	PurchaserId string      `json:"purchaserId"`
	Payment     int         `json:"payment"`
}

type PutOrderReq struct {
	ProductId string      `json:"productId"`
	Products  []*Products `json:"products,optional"`
	Address   string      `json:"address,optional"`
	State     int         `json:"state,optional"`
	Payment   int         `json:"payment,optional"`
}

type ListOrderRequest struct {
	State     int    `form:"state"`
	ShopId    string `form:"shopId"`
	ProductID string `form:"productId"`
	Page      int    `form:"page"`
	Size      int    `form:"size"`
}

type ListOrderResp struct {
	Items []*Order `json:"items"`
	Count int64    `json:"count"`
}

type Order struct {
	OrderId     string      `json:"orderId"`
	Products    []*Products `json:"products"`
	ShopId      string      `json:"shopId"`
	ShopName    string      `json:"shopName"`
	Address     string      `json:"address"`
	State       int         `json:"state"`
	Payment     int         `json:"payment"`
	DriverId    string      `json:"driverId,optional"`
	PurchaserId string      `json:"purchaserId"`
	UpdateTime  int64       `json:"updateTime"`
	CreateTime  int64       `json:"createTime"`
}

type Products struct {
	ProductId   string  `json:"productId"`
	ProductName string  `json:"productName"`
	Price       float64 `json:"price"`
	Count       int     `json:"count"`
}
